In [14]:
import numpy as np
np.__version__

'1.26.4'

In [ ]:
dir(np) 

In [ ]:
help(np.array)

In [ ]:
x = np.array([1,3])
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [9]:
x.ndim

1

In [10]:
x.shape

(2,)

In [11]:
x.size

2

In [12]:
x.dtype

dtype('int32')

In [ ]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [15]:
x.dtype

dtype('float64')

In [18]:
x = np.array([[1,2],[-3,1]])

In [19]:
x.ndim

2

In [20]:
x.shape

(2, 2)

In [22]:
x = np.array([[1,2,3], [4,2,1]])
print(x)

[[1 2 3]
 [4 2 1]]


In [23]:
x.shape

(2, 3)

In [28]:
x = np.array([[[4, 3, 1], 
               [3, 1, 2]],

               [[4, 1, 3], 
                [4, 2, 1]],
               [[4, 5, 5],
                [3, 5, 6]]
               ])

In [29]:
x.ndim

3

In [30]:
x.shape

(3, 2, 3)

In [31]:
A = np.array([1, 2, 3])
A.dtype

dtype('int32')

In [32]:
A = np.array([1.2, 3.4, 5.4])
A.dtype

dtype('float64')

In [33]:
A = np.array([1, 2, 4], dtype=float)
A.dtype

dtype('float64')

In [34]:
A

array([1., 2., 4.])

In [36]:
A = np.array([1,2,3], dtype=complex)
A.dtype

dtype('complex128')

In [39]:
A = np.array([1.2, 3.4, 5.6], dtype=np.int8)
A.dtype

dtype('int8')

In [40]:
A = np.array([1.2, 3.4, 5.6], dtype=np.uint8)
A.dtype

dtype('uint8')

In [41]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [43]:
np.ones(shape=(4, 3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [44]:
np.full(shape=(3,3), fill_value=4, dtype=int)


array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [45]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [48]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [49]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [50]:
A = np.arange(15)
A.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [51]:
A.reshape(3, -1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [52]:
A.reshape(-1, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [53]:
v = np.array([3, 2])
w = np.array([2,-1])
v_plus_w = v + w
print(v_plus_w)


[5 1]


In [55]:
v = np.array([3,1])
przeskalowany_y = 2.0 * v
print(przeskalowany_y)

[6. 2.]


In [56]:
baza = np.array(
    [[3, 0],
     [0, 2]]
)

v = np.array([1, 1])
nowy_y = baza.dot(v)
print(nowy_y)

[3 2]


In [65]:
i_daszek = np.array([2, 0])
j_daszek = np.array([0, 3])
baza = np.array([i_daszek, j_daszek]).transpose()
v = np.array([1,1])
nowy_v = baza.dot(v)
print(nowy_v)

[2 3]


In [66]:
#Obliczanie wyznacznika
from numpy.linalg import det
from numpy import array
i_daszek = array([3,0])
j_daszek = array([0,2])
baza = array([i_daszek, j_daszek]).transpose()
wyznacznik = det(baza)
print(wyznacznik)


6.0


In [67]:
#wyznacznik w przypadku ścięcia
from numpy.linalg import det
from numpy import array
i_daszek = array([1,0])
j_daszek = array([1,1])
baza = array([i_daszek, j_daszek]).transpose()
wyznacznik = det(baza)
print(wyznacznik)

1.0


In [68]:
A = np.array([3,1,4,2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [69]:
A + B

array([6, 0, 7, 4])

In [70]:
A - B

array([0, 2, 1, 0])

In [71]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [72]:
A + 3

array([6, 4, 7, 5])

In [73]:
X = np.array([[1,3], [-2, 0]])
Y = np.array([[6,0],[-1,2]])
print(X)
print(Y)

[[ 1  3]
 [-2  0]]
[[ 6  0]
 [-1  2]]


In [74]:
X * Y

array([[6, 0],
       [2, 0]])

In [76]:
#mnożenie macierzy wersz * kolumna
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [77]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [78]:
np.random.seed(0)

In [79]:
#losowa wartość z rozkładu normalnego
np.random.randn()

1.764052345967664

In [80]:
np.random.randn(10, 4)

array([[ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799],
       [-0.97727788,  0.95008842, -0.15135721, -0.10321885],
       [ 0.4105985 ,  0.14404357,  1.45427351,  0.76103773],
       [ 0.12167502,  0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574, -2.55298982],
       [ 0.6536186 ,  0.8644362 , -0.74216502,  2.26975462],
       [-1.45436567,  0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252, -0.88778575],
       [-1.98079647, -0.34791215,  0.15634897,  1.23029068],
       [ 1.20237985, -0.38732682, -0.30230275, -1.04855297]])

In [85]:
np.random.choice([1,2,3,4,5])

4

In [87]:
np.random.shuffle([1,2,4,5,6,7])

In [5]:
np.exp(2)

7.38905609893065

In [6]:
np.sqrt(9)

3.0

In [8]:
np.all([1,3,4,1])

True

In [13]:
np.any([0,0,0,0])

False

In [15]:
bool(0)

False

In [16]:
A = np.random.rand(5)
A

array([0.41522525, 0.96633718, 0.54193463, 0.80451625, 0.56206772])

In [17]:
np.argmax(A)

1

In [19]:
A[np.argmax(A)] - A

array([0.55111193, 0.        , 0.42440256, 0.16182094, 0.40426947])

In [3]:
from sympy import *
#4x + 2y + 4z = 44
#5x + 3y + 7z = 56
#9x + 3y + 6z = 72
A = Matrix([
    [4,2,4],
    [5,3,7],
    [9,3,6]
])
# Pomonożenie macierzy przez jej odwrotność daje wyniku macierz jednostkowa
odwrotna = A.inv()
jednostkowa = odwrotna * A
print("Macierz odwrotna: {}".format(odwrotna))
print("Macierz jednostkowa: {}".format(jednostkowa))
B = Matrix([
    44,
    56,
    72
])
X = A.inv() * B
print(X)

Macierz odwrotna: Matrix([[-1/2, 0, 1/3], [11/2, -2, -4/3], [-2, 1, 1/3]])
Macierz jednostkowa: Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
Matrix([[2], [34], [-8]])


In [ ]:
for row in A:
    print(row)

In [4]:
A.shape

(3, 3)

In [10]:
A.reshape(3,3)

Matrix([
[4, 2, 4],
[5, 3, 7],
[9, 3, 6]])

In [12]:
A.T

Matrix([
[4, 5, 9],
[2, 3, 3],
[4, 7, 6]])

In [18]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
print(A)

[[-10.   -9.5  -9.   -8.5]
 [ -8.   -7.5  -7.   -6.5]
 [ -6.   -5.5  -5.   -4.5]
 [ -4.   -3.5  -3.   -2.5]
 [ -2.   -1.5  -1.   -0.5]
 [  0.    0.5   1.    1.5]
 [  2.    2.5   3.    3.5]
 [  4.    4.5   5.    5.5]
 [  6.    6.5   7.    7.5]
 [  8.    8.5   9.    9.5]]


In [19]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [20]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [21]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [22]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])