In [1]:
import numpy as np
np.__version__

'1.26.4'

In [2]:
price = np.array(
    [
        [12.40, 12.80, 11.90, 12.60, 1000],
        [12.50, 13.00, 11.70, 12.20, 2000],
        [12.20, 13.40, 11.20, 13.20, 1500],
    ]
)

In [3]:
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   11.2   13.2 1500. ]]


In [4]:
price.sum()

4649.1

In [ ]:
# sumujemy kolumny
price.sum(axis=0)

array([  37.1,   39.2,   34.8,   38. , 4500. ])

In [6]:
# sumujemy wiersze
price.sum(axis=1)

array([1049.7, 2049.4, 1550. ])

In [7]:
np.median(price)

12.6

In [8]:
np.mean(price, axis=0)

array([  12.36666667,   13.06666667,   11.6       ,   12.66666667,
       1500.        ])